# Generated by Django 3.0.6 on 2020-09-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=255, unique=True, verbose_name='User ID')),
                ('phone_number', models.CharField(max_length=15, default='', verbose_name='Phone Number')),
                ('api_key', models.CharField(max_length=50, default='', verbose_name='API Key')),
                ('api_expire_date', models.DateTimeField(verbose_name='API Expire Date')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
